name: Deploy Lambda Function

on:
  push:
    branches:
      - develop
      - feature/workflow

env:
  AWS_REGION: us-east-1
  TF_VAR_aws_region: us-east-1

jobs:
  Validate:
    name: Validate Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

  Plan:
    name: Plan Terraform Changes
    runs-on: ubuntu-latest
    needs: Validate

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -var-file="terraform.fvars" -out=tfplan

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: terraform-artifacts
        path: |
          tfplan
          .terraform.lock.hcl

  Apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    needs: Plan

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: terraform-artifacts

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
